public class EvenFibonacciNumbers {

    //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    //
    //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    //
    //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


    public static void main(String[] args) {

        long limit = 4000000;

        System.out.println(eventFib(limit));

    }

    static long fib(long n) {
        if ((n == 0) || (n == 1))
            return n;
        else
            return fib(n - 1) + fib(n - 2);
    }


    static long eventFib(long limit) {
        long sum = 0;
        long a = 1;
        long b = 1;
        long c;
        while (b < limit) {
            if (b % 2 == 0) {
                sum = sum + b;
            }
            c = a + b;
            a = b;
            b = c;
        }
        return sum;
    }
}


